### ISSUE TITLE
spurl: !secret spurl in each device

### ISSUE THREAD

**Issue by plouf34** [devmel/hass_airsend#1]
Hello
For Local Mode, what does it mean "spurl: !secret spurl in each device"?
How and where in HA to do that after to install the Local mode addon?

**Comment by jujupointcom** [comment]
Hello,
If I am correct, in the configuration.yaml, you must add spurl: !secret spurl like this :
```
airsend:
  devices:
    Store:
      id: 22261
      type: 4098
      apiKey: "yourapikey"
      **spurl: !secret spurl**
      channel:
         id: 13920
         source: 7483923
```
And then in your secrets.yaml file
`spurl : sp//password_ontheback_of_your_device@local_IP_address_of your_airsend`
